### ISSUE TITLE
Keep requests when broken

### ISSUE THREAD

**Issue by jeytee84** [AlmostReliable/merequester#12]
### Describe the feature/addition!

Breaking a requester should save the request settings inside.

### Why would like to see this feature/addition?

This way moving them wouldn't be a pain.

**Comment by rlnt** [comment]
Hmm, I thought about this but what would be a good way to reset them then so they stack again?
Maybe I only check for the item slots if they have something configured and if all are empty, nothing is saved.

I initially planned to implement that you can copy the settings with a memory card but I don't know if that would be obvious to most users.

**Comment by jeytee84** [comment]
I was hoping the memory card way was a thing, for me it would have been obvious if for example there was a card slot in the gui. Also it would probably be the best and most immersive way. In the tooltip you could write something like "Request settings deleted when broken, use a memory card to save/transfer them" 

But to be honest anything that's easy to implement would work. Saving them by default and just running it through a crafting grid to wipe would be also lovely. Or even saving them only when removed with a wrench (but imo that's less user-friendly).

**Comment by jeytee84** [comment]
well that was fast :D :D thanks for everything

**Comment by jeytee84** [comment]
Btw just to show my appreciation, the other day on my AOF6 playthrough i kinda felt burned out because it always felt like a pain setting up the me system and building the autocrafting buffers with interfaces. When i went to bed, i had the idea to look up if there was a solution for it, found your mod and actually was excited to play again, been playing ever since. Cheers!
