### ISSUE TITLE
The hud size is not adjustable.

### ISSUE THREAD

**Issue by bypgomes** [AlmostReliable/merequester#15]
[###] Version

1.19.2 - FORGE

### Describe the bug!

It is not possible to modify the size of the interface, either in the terminal or in the block.
Version - 1.19.2 - 1.1.3 
https://i.imgur.com/CSgpxjp.png

### Additional Context

Yes

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
It's a terminal size setting, of course, it won't be available inside the block.
And for the terminal, I don't know exactly what you mean. You just provided a single image without any context so what do you expect?

For me, the button is working.

https://github.com/AlmostReliable/merequester/assets/16513358/82a44eaf-00aa-4d7b-936a-27b3dd4c8886

**Comment by bypgomes** [comment]
In my case, I play in full screen, the interface tries to fill the entire screen in both the terminal and the request I'm using with 64 spaces, I don't know if that interferes with something.

**Comment by rlnt** [comment]
Okay, I can reproduce this if I set the config option to 64. I'll take a look.
