### ISSUE TITLE
1.1.4 autocrafting random items in 1.20.1

### ISSUE THREAD

**Issue by aAndrew3030** [AlmostReliable/merequester#17]
### Version

1.20.1-1.1.4

### Describe the bug!

After updating to 1.1.4, all my terminals that can craft started crafting a random item until the drive is full! In my case, 700k leaf poncho chestplates lul. Removing the requester terminal stopped the crafting. Everything in the terminal and requesters were blank (as I haven't used them yet). If your unable to recreate the issue, I can try to narrow down possible mod conflicts, as I am using a large pack

### Additional Context

Yes

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by rlnt** [comment]
Hmm, that sounds odd. I didn't change any crafting logic in 1.1.4. I am also not able to reproduce this in my own instance.

Can you still reproduce this? This issue slipped through my notifications and it's been 2 weeks. Sorry about that.

**Comment by Slexom** [comment]
Having the same issue playing on AOF7 server that use 1.1.4 .
To me it start requesting some raw ore despite I don't have any recipe set for them in any pattern provider for example. I think it depend on the recipe it should start instead. For example instead to craft aluminum drill, it try to craft raw aluminum.

As you can see from the screenshot, the requester is trying to craft raw ore without succes, blocking the cpu.
![2024-01-27_00 55 23](https://github.com/AlmostReliable/merequester/assets/9221469/3c9cd471-b43f-4bc4-9644-c1274e2134c5)

Here some of the recipes I've set. Plus drills an uranium rod at the bottom.
![2024-01-27_00 55 10](https://github.com/AlmostReliable/merequester/assets/9221469/e1601638-5914-4462-b155-a3f9ffa89103)

Opened a new issue regarding this: https://github.com/AlmostReliable/merequester/issues/20
