### ISSUE TITLE
1.1.4 for Fabric 1.20.1 - Random items auto crafted

### ISSUE THREAD

**Issue by Slexom** [AlmostReliable/merequester#20]
### Version

ME Requester 1.1.4 in AOF7 1.2.2

### Describe the bug!

Having this issue playing on AOF7 server that use 1.1.4 .
It start requesting some raw ore despite I don't have any recipe set for them in any pattern provider for example. I think it depend on the recipe it should start instead. For example instead to craft aluminum drill, it try to craft raw aluminum.

As you can see from the screenshot, the requester is trying to craft raw ore without succes, blocking the cpu.
![2024-01-27_00 55 23](https://github.com/AlmostReliable/merequester/assets/9221469/3c9cd471-b43f-4bc4-9644-c1274e2134c5)

Here some of the recipes I've set. Plus drills and uranium rod at the bottom.
![2024-01-27_00 55 10](https://github.com/AlmostReliable/merequester/assets/9221469/e1601638-5914-4462-b155-a3f9ffa89103)

### Additional Context

Yes

### Modifications

AOF7 modpack, nothing more or less than that

### Did the issue happen in singleplayer or on a server?

Server

**Comment by rlnt** [comment]
Odd behavior especially since I've only heard about this issue from two people now (you and the other issue). I can't reproduce this and also can't explain why this would happen if you don't even have a pattern set up for the recipe it's trying to craft.

The requester only requests the craft for the item you configured in one of the slots like a player would. The craft of the dependency ingredients is handled by AE2 itself. Would you be able to provide the world you are playing somewhere as a download so I can remote debug it in a development environment? If I can't reproduce the issue on my own, there is no way for me to figure out what's happening.

**Comment by Slexom** [comment]
I can try in single player to reproduce it and give you the world.
I've also checked logs to see if could have some info about this behavior but nothing...

**Comment by Slexom** [comment]
Sorry, I was unable to replicate the issue in single player. While in multiplayer I can confirm it persists.

**Comment by wu452148993** [comment]
I also encountered this problem, and I found that it only occurred when the forge tps was low. I tried to modify merequest block refresh speed and it is not valid.

**Comment by wu452148993** [comment]
> Sorry, I was unable to replicate the issue in single player. While in multiplayer I can confirm it persists.

Do you use extened molecular assembler(it in extendedae mod)?I suspect this machine is causing the problem

**Comment by rlnt** [comment]
> Sorry, I was unable to replicate the issue in single player. While in multiplayer I can confirm it persists.

Would you be able to share the world? I can also debug it in multiplayer but I need a local copy.

**Comment by Slexom** [comment]
> > Sorry, I was unable to replicate the issue in single player. While in multiplayer I can confirm it persists.
> 
> Would you be able to share the world? I can also debug it in multiplayer but I need a local copy.

I can try asking the server admins. Anyway, the server is the official All Of Fabric 7, EU Region.

Anyway, could be related to low TPS maybe, the server run often on the range 13-17 for long time. But yes, without a way to reproduce it is hard to say...

Here another screenshot, the timer also go crazy, specially when fluids are involved in the recipe.

![2024-01-31_20 54 04](https://github.com/AlmostReliable/merequester/assets/9221469/e137c4b6-446f-4cf3-9116-9a073dd70cde)

**Comment by wu452148993** [comment]
I suggest change "CRAFT_LESS" to "REPORT_MISSING_ITEMS". Although it may not completely solve the problem, setting a larger number of composites can reduce the probability of the problem occurring.
