### ISSUE TITLE
Items crafted on other disconnected networks

### ISSUE THREAD

**Issue by 77wisher77** [AlmostReliable/merequester#21]
### Version

1.1.4-1.20.1

### Describe the bug!

When requesting items sometimes they get crafted on other peoples networks, completely disconnected, separate dimension, no way they can communicate yet the crafting cpus are being used

the particular item in this case is sugar from vanilla minecraft, tried 2 different physical requesters

### Log

https://pastebin.com/UPHC0RJm

### Additional Context

Yes

### Modifications

ATM9 modpack, happened across multiple versions, currently on `0.2.42`

### Did the issue happen in singleplayer or on a server?

Server

**Comment by 77wisher77** [comment]
also this is on forge

**Comment by rlnt** [comment]
Could you provide the world so I can debug this? There should be no way this could happen. The mod internally uses the standard AE2 behavior for submitting crafting jobs, as a player would.

**Comment by 77wisher77** [comment]
Sure

a thought did just occur, i dont have any sugar cane, and the system that is crafting it does have sugar cane

will have the world uploaded in a minute

**Comment by 77wisher77** [comment]
Server World: [World](https://www.dropbox.com/scl/fi/58m7g147l9b1dvf30ob5x/world.zip?rlkey=sxyr3bfkemv7dkl6y1ulqlb5z&dl=0)

Requesting system: Allthemodium:mining 18194, 253, -6780
crafting (external) system: allthemodium:beyond 40188, 64 , 26871

**Comment by rlnt** [comment]
Did you host that on a dedicated server or did you open it to LAN? Some issues only appear when playing on a server and I need to know how this was set up to properly debug it.

I'll try to find the issue when I find the time. Thanks for the world.

**Comment by 77wisher77** [comment]
manually requesting sugar uses my crafting cpus, just tested a bunch, me requesters dont seem to use my system

**Comment by 77wisher77** [comment]
> Did you host that on a dedicated server or did you open it to LAN? Some issues only appear when playing on a server and I need to know how this was set up to properly debug it.
> 
> I'll try to find the issue when I find the time. Thanks for the world.

Dedicated server

**Comment by andriihorpenko** [comment]
@rlnt looks like this odd behavior _vanishes_ when you uncheck unused rows. This was tested for three consequent days - got zero occurrences, so seems like this might be it. Hopefully this helps.
