### ISSUE TITLE
Request config doesn't appear to work

### ISSUE THREAD

**Issue by MunchyG** [AlmostReliable/merequester#23]
### Minecraft Version

1.20.1 ATM9 NF

### Mod Version

merequester-forge-1.20.1-1.1.4

### Describe the bug!

changing the requests value in the merequester-common.toml appears to have no effect. i have tried it on both a server and single player. 

### Additions and Modifications

Yes

### Did the issue happen in singleplayer or on a server?

Both

**Comment by rlnt** [comment]
Working fine for me on the same version: ![](https://i.imgur.com/TiyS9R7.png)

**Comment by MunchyG** [comment]
i restarted my pc and now it works. i was reading on discord you needed to restart both the server and the client, but that didn't seem to fix it.

**Comment by trevorjd** [comment]
Hi,

Playing ATM10 v2.7 with merequester-neoforge-1.21.1-1.1.8
I changed the server side config to "requests = 25", saved and restarted the server and restarted the client.  Unfortunately in-game, I still only have the default 5 request slots. 
I checked the config on the client, and it still only reads 5.  After manually updating the client side config, I have 25.
So it looks like config on the server is not being correctly pushed to the client.
If I can test any further, please let me know what you'd like me to do.

Cheers

**Comment by SapphireMH** [comment]
> After manually updating the client side config, I have 25. So it looks like config on the server is not being correctly pushed to the client.

I can confirm that this bug still exists, and is reproducible following the steps taken by @trevorjd 

Perhaps @AlmostReliable is unaware because we've commented on an already closed issue?

I'll submit a new issue.
