### ISSUE TITLE
Suggestion: Add a feature to keep items in system unless over a certain amount

### ISSUE THREAD

**Issue by Hazmatik** [AlmostReliable/merequester#25]
### Describe the feature/addition!

It could be added as a feature of the Requester or as a separate block called "Stocker" or something that will prevent items from being exported via export buses unless it's over a certain amount.

### Why would like to see this feature/addition?

This is currently a feature that can be done using a level emitter on an export bus, but doing so uses a channel and usually leaves ugly cabling that sometimes can be difficult to fit around machines that need items, fluids, energy and gases for Mekanism connected.

**Comment by rlnt** [comment]
I think this is out of scope and I won't implement this. Something like this would be hidden behavior and there would be no indicator on an export bus that another node in the grid is disabling them. This would also require to iterate over each export bus in the network and to consider if the specific bus needs disabling which is a performance concern. Also, level emitters don't take a channel so I don't see a reason for this besides the aesthetics.
