### ISSUE TITLE
1.18.2 backport please

### ISSUE THREAD

**Issue by MSandro** [AlmostReliable/merequester#3]
### Describe the feature/addition!

it would be great if you could backport the mod to 1.18.2

### Why would like to see this feature/addition?

I would like to use the mod in my Modpack Sky FABRICation 3

**Comment by rlnt** [comment]
The requester is available in Lazier AE2 for 1.18.2.

I just decided to split it off of the mod for 1.19 and the future to make the development faster and more efficient. So if you need something like that, you should consider installing Lazier AE2. A backport won't happen for the standalone version, sorry.

**Comment by rlnt** [comment]
Oh, you are on Fabric. That's unfortunate because Lazier AE2 is Forge only. Sorry about that but a backport is just not worth it anymore.

**Comment by MSandro** [comment]
Ok thanks for the fast reply

**Comment by rlnt** [comment]
Well, I changed my mind and made a 1.18 backport for Forge and Fabric. @MSandro
It should be available in a bit when the review is done on CurseForge.

**Comment by MSandro** [comment]
Wow nice, thank you very much
