### ISSUE TITLE
Config Option

### ISSUE THREAD

**Issue by nutellabrot155** [AlmostReliable/merequester#33]
### Minecraft Version

1.20.1

### Mod Version

1.1.5

### Describe the bug!

I tried to edit the number of request one single requester can do,but it doesnt work on my server

### Additions and Modifications

Yes

### Did the issue happen in singleplayer or on a server?

Multiplayer

**Comment by nutellabrot155** [comment]
After some testing i found out that u need to change the value in both server and client;So im assuming there is an errror with config sync when joining a server

**Comment by rlnt** [comment]
Config sync isn't a thing. The mod uses the built-in config system by the respective loader.
