### ISSUE TITLE
JEI Drag & ME Requester

### ISSUE THREAD

**Issue by dKatsuro** [AlmostReliable/merequester#34]
### Minecraft Version

1.21.1

### Mod Version

ME Requester v1.1.8 / All The Mods 10 v1.1.8

### Describe the bug!

With a lot of AE2, you are able to simply drag items (or fluids) from JEI into importers, exporters, etc.

It seems you are unable to do the same with the ME Requester or the ME Requester Terminal. When I do start dragging something from JEI, the slots in the ME Requesters/Terminal does highlight green, like it's a slot you are able to drag do. But, won't accept whatever I'm dragging in.

Pretty easy to workaround if it's an item, as I can just grab the item. But, if I wanted to make requests for a fluid it does not work as using a fluid bucket would literally want to craft buckets of said fluid instead. 

### Additions and Modifications

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by rlnt** [comment]
AE2 has no first-party support for JEI on 1.21+. I am using the provided AE2 packet to perform the drag-and-drop action. It is working fine with EMI since AE2 has support for that.
You might want to report that to the [integration mod](https://github.com/Tamaized/AE2-JEI-Integration) instead.

**Comment by puggan** [comment]
Integration mod says they not going to do it, and says "This is an issue for ME Requester"

https://github.com/Tamaized/AE2-JEI-Integration/issues/3

Any chance that you reconsider and add it?

**Comment by pipman3000-rettata** [comment]
Just from taking a glance at the integration code, it seems like they're sending ae2 packets with the ghost handler.  Not sure what's causing the bug, but this leads me to believe the bug is with ME Requester, not the integration layer.

https://github.com/Tamaized/AE2-JEI-Integration/blob/9b40f2f950db98d7bed72ffcdffb1c03495cef15/src/main/java/tamaized/ae2jeiintegration/integration/modules/jei/GhostIngredientHandler.java#L80-L105

**Comment by rlnt** [comment]
I am already making use of the drag and drop packet AE2 is using as well, so the mod adding integration for JEI should cover that. I can revisit this in the next few days and take a look, since I got a bit of time, no promises though.

**Comment by pipman3000-rettata** [comment]
I appreciate you replying regardless of whatever happens.  I think I've already narrowed it down a bit further though.  It appears that when the SET_FILTER action is sent, InventoryActionPacket calls the setFilter method on the AEBaseMenu in player.containerMenu:

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/fd8b717a405672ce4f65ba540f1db8c91317daa4/src/main/java/appeng/core/network/serverbound/InventoryActionPacket.java#L59-L67

 https://github.com/AlmostReliable/merequester/blob/81bdf25194422f92f71a4e98dca506f4d18da5c4/src/main/java/com/almostreliable/merequester/requester/abstraction/AbstractRequesterMenu.java

And looking at AbstractRequesterMenu, there's no implementation of setFilter.  So, this base implementation must not be able to handle what's going on in the requester:

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/fd8b717a405672ce4f65ba540f1db8c91317daa4/src/main/java/appeng/menu/AEBaseMenu.java#L544-L559

I'm seeing if I can just fix it myself and submit a pull request but my grasp on java mainly comes from C# and I have zero experience with minecraft mod making, so no promises here either lol

<blockquote><img src="https://opengraph.githubassets.com/f1e6bfeb51343693716a58a488822bf6eda12b8a3c54f69881fdf147c74c2fe6/AppliedEnergistics/Applied-Energistics-2" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/fd8b717a405672ce4f65ba540f1db8c91317daa4/src/main/java/appeng/core/network/serverbound/InventoryActionPacket.java">Applied-Energistics-2/src/main/java/appeng/core/network/serverbound/InventoryActionPacket.java at fd8b717a405672ce4f65ba540f1db8c91317daa4 · AppliedEnergistics/Applied-Energistics-2</a></strong></div><div>A Minecraft Mod about Matter, Energy and using them to conquer the world.. - AppliedEnergistics/Applied-Energistics-2</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/41eb3e33ac1778e3315d84a2b20a71dc1b75737f8e816cdc987e838d6d782ecb/AlmostReliable/merequester" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/AlmostReliable/merequester/blob/81bdf25194422f92f71a4e98dca506f4d18da5c4/src/main/java/com/almostreliable/merequester/requester/abstraction/AbstractRequesterMenu.java">merequester/src/main/java/com/almostreliable/merequester/requester/abstraction/AbstractRequesterMenu.java at 81bdf25194422f92f71a4e98dca506f4d18da5c4 · AlmostReliable/merequester</a></strong></div><div>A Minecraft mod to keep items and fluids in your Applied Energistics 2 ME-System in stock. - AlmostReliable/merequester</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/f1e6bfeb51343693716a58a488822bf6eda12b8a3c54f69881fdf147c74c2fe6/AppliedEnergistics/Applied-Energistics-2" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/fd8b717a405672ce4f65ba540f1db8c91317daa4/src/main/java/appeng/menu/AEBaseMenu.java">Applied-Energistics-2/src/main/java/appeng/menu/AEBaseMenu.java at fd8b717a405672ce4f65ba540f1db8c91317daa4 · AppliedEnergistics/Applied-Energistics-2</a></strong></div><div>A Minecraft Mod about Matter, Energy and using them to conquer the world.. - AppliedEnergistics/Applied-Energistics-2</div></blockquote>

**Comment by pipman3000-rettata** [comment]
I was wrong.  The fault lies with the integration mod.  These lines specifically:

https://github.com/Tamaized/AE2-JEI-Integration/blob/9b40f2f950db98d7bed72ffcdffb1c03495cef15/src/main/java/tamaized/ae2jeiintegration/integration/modules/jei/GhostIngredientHandler.java#L101-L102

If those lines are simply replaced with
`slot.setFilterTo(wrapped);`
then the requester starts working fine.

I'm going to continue this in the issue on the integration mod's side.

<blockquote><img src="https://opengraph.githubassets.com/6f7c06f9addbb9825978996ba0b5e04e295ca3defd9e1b6d7f243c3079e6c8b4/Tamaized/AE2-JEI-Integration" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Tamaized/AE2-JEI-Integration/blob/9b40f2f950db98d7bed72ffcdffb1c03495cef15/src/main/java/tamaized/ae2jeiintegration/integration/modules/jei/GhostIngredientHandler.java">AE2-JEI-Integration/src/main/java/tamaized/ae2jeiintegration/integration/modules/jei/GhostIngredientHandler.java at 9b40f2f950db98d7bed72ffcdffb1c03495cef15 · Tamaized/AE2-JEI-Integration</a></strong></div><div>Contribute to Tamaized/AE2-JEI-Integration development by creating an account on GitHub.</div></blockquote>

**Comment by rlnt** [comment]
This issue has been fixed by the AE2 JEI integration mod.
